# Current Execution
spring.jpa.hibernate.ddl-auto = update
# Spring Configuration
# USER, DATABASE_IP, DATABASE and PASSWORD are Environment Variables
spring.application.name=miteve-api
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.username = ${USER}
spring.datasource.url = jdbc:postgresql://${DATABASE_IP}:5432/${DATABASE}
spring.datasource.password = ${PASSWORD}
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql = true
# API
access=new-api
server.port=${PORT}
# Endpoints
endpoint.containers=${access}/containers
endpoint.contents=${access}/contents
endpoint.episodes=${access}/episodes
endpoint.utils=${access}/utils